name: first-workflow
on: workflow_dispatch
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Print Greet
              run: | 
                  echo "hello buddy"
                  echo "this is the second line"
                  echo "third command to check how to pass multiline statements"
            - name: Print GoodBye
              run: echo "Done bYE BYE !!"
